# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 01 Sep 2016 01:31:28 +0000
*	@ALL	0
*	@read	1
start	@ALL	1
work:炫智:*	@ALL	1
