<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: gavin
 * Date: Thu, 01 Sep 2016 20:52:24 +0800
 */

$conf['title'] = 'Wiki';
$conf['lang'] = 'zh';
$conf['template'] = 'codowik';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile_delete,source,export_raw';
$conf['fnencode'] = 'utf-8';

// end auto-generated content
